[build]
  publish = "dist/"
  command = "yarn run build"

[build.environment]
  NODE_ENV = "production"

[dev]
  framework = "#custom"
  command = "yarn run preview"
  publish = "dist"
  targetPort = 4000
  port = 4001

[[redirects]]
  from = "/projects/prideify"
  to = "https://github.com/alexpeattie/prideify"

[[redirects]]
  from = "/projects/windowed"
  to = "https://github.com/alexpeattie/windowed"

[[redirects]]
  from = "/projects/justvector_icons"
  to = "/projects/justvector-icons"

[[redirects]]
  from = "/projects/animate-textshadow"
  to = "https://alexpeattie.com/blog/retiring-animate-textshadow-floating-feedback#animate-textshadowjs"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404 
  